import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const highlights = [
  { title: "Tailoring", copy: "Refined silhouettes shaped with intention, balance and beautiful movement.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F861405e2713d469cb6285abe561d1b08?format=webp&width=1600&height=2400&quality=95" },
  { title: "Fabric Sourcing", copy: "Thoughtful textures and premium materials chosen for how they feel and endure.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Ffb3a131489e746a6bea711e9fe46b3c0?format=webp&width=1600&height=2400&quality=95" },
  { title: "Attention to Detail", copy: "Quiet finishing touches that make every Amelie piece feel distinctly personal.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F223f9b961ecb479a8f7d48d18d39ee28?format=webp&width=1600&height=2400&quality=95" },
  { title: "Considered Production", copy: "A slower, more intentional approach to creating pieces made to be lived in.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F89629c8dbe52489fbaf2c087398e5bd1?format=webp&width=1600&height=2400&quality=95" },
];

const About = () => (
  <div className="min-h-screen bg-[#F0E9E2] text-[#0F0F0F]">
    <Header />
    <main>
      <section className="relative min-h-[620px] md:h-[700px] overflow-hidden bg-stone-900 flex items-end"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F9bd2b790b1514a22af7615257f60ceaf?format=webp&width=1800&height=2700&quality=95" alt="Amelie Milano signature fashion" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-stone-950/70 via-stone-950/15 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-16 md:pb-20 text-white"><p className="text-[10px] uppercase tracking-[0.28em] text-white/80 mb-5">The House of Amelie</p><h1 className="font-serif text-6xl md:text-8xl leading-[0.86] max-w-2xl mb-6">About Amelie Milano</h1><p className="text-sm md:text-base text-white/85 max-w-md leading-relaxed mb-8">Luxury Italian-inspired fashion for the modern woman.</p><Link to="#vision" className="inline-flex items-center gap-3 bg-[#C69B6D] px-6 py-3 text-xs uppercase tracking-[0.16em] text-stone-900 hover:bg-white transition-colors">Discover Our Vision <ArrowRight size={15} /></Link></div></section>

      <section id="vision" className="bg-[#F0E9E2] py-20 md:py-32"><div className="container mx-auto px-4"><div className="grid md:grid-cols-2 gap-10 md:gap-20 items-center"><div className="max-w-lg"><p className="text-teal text-[10px] uppercase tracking-[0.28em] mb-5">Our Philosophy</p><h2 className="font-serif text-4xl md:text-6xl mb-6">Italian elegance.<br />Bengali soul.</h2><p className="text-stone-600 leading-relaxed mb-5">Amelie Milano is a premium Italian-inspired fashion and lifestyle house for the modern woman. We bring together the romance of European craftsmanship, the warmth of our Bengali perspective and the confidence of contemporary femininity.</p><p className="text-stone-600 leading-relaxed">Our collections are designed to feel timeless rather than temporary — considered pieces that accompany the way you move, celebrate and live.</p></div><div className="overflow-hidden"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F77539d98f20c4d2183d39c92920916b5?format=webp&width=800&height=1200" alt="Amelie Milano editorial fashion" className="w-full aspect-[4/5] object-cover" /></div></div></div></section>

      <section className="bg-white py-16 md:py-24"><div className="container mx-auto px-4"><div className="text-center mb-10"><p className="text-teal text-[10px] uppercase tracking-[0.28em] mb-3">The Amelie Standard</p><h2 className="font-serif text-4xl md:text-5xl">Made with intention</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-5 md:gap-7">{highlights.map((highlight) => <article key={highlight.title} className="group"><div className="overflow-hidden mb-5"><img src={highlight.image} alt={highlight.title} className="w-full aspect-[3/4] object-cover group-hover:scale-[1.03] transition-transform duration-500" /></div><h3 className="font-serif text-2xl group-hover:text-teal transition-colors">{highlight.title}</h3><p className="text-sm text-stone-600 leading-relaxed mt-3">{highlight.copy}</p></article>)}</div></div></section>

      <section className="relative min-h-[430px] overflow-hidden flex items-center"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F87192a4e5d0949b8b89c181ebaa5ef28?format=webp&width=1800&quality=95" alt="Inspired by Italy, designed for you" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-stone-950/35" /><div className="relative z-10 container mx-auto px-4 text-center text-white"><p className="text-[10px] uppercase tracking-[0.28em] mb-5">Design Inspiration</p><h2 className="font-serif text-5xl md:text-7xl">Inspired by Italy,<br />Designed for You</h2></div></section>

      <section className="bg-[#F0E9E2] py-16 md:py-24"><div className="container mx-auto px-4"><div className="grid md:grid-cols-2 gap-10 md:gap-20 items-center"><div className="overflow-hidden md:order-2"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F0d9a3c2952174eeab2c250230e284f76?format=webp&width=1600&height=2400&quality=95" alt="Amelie Milano founder story" className="w-full aspect-[4/5] object-cover" /></div><div className="max-w-lg md:order-1"><p className="text-teal text-[10px] uppercase tracking-[0.28em] mb-5">The Founder Story</p><h2 className="font-serif text-4xl md:text-5xl mb-6">A vision for modern femininity.</h2><p className="text-stone-600 leading-relaxed mb-6">Amelie Milano began with a simple belief: getting dressed should feel like stepping into your own story. From our home in Bangladesh, we look to the ease of Milan, the artistry of Italian design and the women who make every day their own.</p><blockquote className="font-serif italic text-2xl text-teal border-l-2 border-[#C69B6D] pl-5">“Elegance is not a moment. It is the way you choose to move through the world.”</blockquote></div></div></div></section>

      <section className="bg-[#E8D7C5] py-16 md:py-24 text-center"><div className="container mx-auto px-4 max-w-2xl"><p className="text-teal text-[10px] uppercase tracking-[0.28em] mb-5">Amelie Milano</p><h2 className="font-serif text-4xl md:text-6xl mb-7">Explore our collections</h2><Link to="/shop/new" className="btn-primary inline-flex">Shop Now</Link></div></section>
    </main>
    <Footer />
  </div>
);

export default About;
