import { ArrowLeft, ArrowRight, ChevronRight } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Breadcrumbs from "@/components/Breadcrumbs";
import { fetchBuilderEditorial, type BuilderEditorialData } from "@/lib/builder";

const articles = {
  "italian-tailoring": { tag: "Fashion", title: "The Art of Italian Tailoring", dek: "Explore the quiet craft behind a considered silhouette.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F92b67c169b484849bc0557782bc3580b?format=webp&width=1400&quality=95", intro: "Italian tailoring is an exercise in restraint. It is the balance between structure and movement, between a precise shoulder and the ease of a fabric that follows the body.", sections: [["The beauty of intention", "A considered garment begins long before it reaches the wardrobe. Proportion, texture and line are brought together with patience, so the final silhouette feels effortless rather than overworked."], ["Made for movement", "The most memorable pieces do not ask a woman to become someone else. They make room for her own rhythm, carrying the quiet confidence of thoughtful construction from morning light to evening."], ["The Amelie point of view", "At Amelie Milano, Italian inspiration becomes a modern Bangladesh wardrobe: refined, expressive and designed to be returned to season after season."]] },
  "wardrobe-essentials": { tag: "Style Tips", title: "Building a Wardrobe With Ease", dek: "The pieces, proportions and textures that make dressing feel effortless.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F25041026487d4444b5d4fdcd8344b030?format=webp&width=1400&quality=95", intro: "A wardrobe with ease is not defined by how much it holds, but by how naturally every piece works together. The strongest foundations leave space for personality.", sections: [["Begin with a point of view", "Choose a palette and a few silhouettes that feel true to you. A considered colour story lets fabrics and proportions become the detail."], ["Layer texture, not noise", "Pair fluid satin with a sculpted knit, or a clean dress with an expressive accessory. Contrast makes familiar pieces feel newly considered."], ["Keep the pieces you return to", "The essentials are the garments that make you feel composed without effort. They earn their place through repetition, not trend."]] },
  "softer-pace": { tag: "Lifestyle", title: "A Softer Pace of Living", dek: "Finding beauty in the rituals that shape an ordinary day.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F8643453bf7a947959862f314163ce4f6?format=webp&width=1400&quality=95", intro: "There is a particular luxury in giving an ordinary moment your full attention. A slower morning, a familiar scent and the small rituals that return us to ourselves.", sections: [["A ritual can be small", "Light, texture and scent can change the feeling of a room. The simplest gestures become meaningful when they are made with intention."], ["Make room for the in-between", "Not every day needs to be optimized. The pauses between plans are where we notice what restores us."], ["Carry the feeling with you", "A softer pace is not about doing less of everything. It is about choosing what deserves your presence."]] },
  "occasion-edit": { tag: "Editorial", title: "The Occasion Edit", dek: "Dressing for evenings that deserve to be remembered.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Feddf3358484d4793b2020549afc8bf06?format=webp&width=1400&quality=95", intro: "The best occasion dressing begins with a feeling. Before the colour or the silhouette, consider how you want to move through the room and what you want to remember.", sections: [["Start with the atmosphere", "A candlelit dinner, a summer celebration and a formal evening each call for a different kind of ease. Let the setting guide the mood, not dictate it."], ["Let one detail lead", "A sculpted shoulder, a luminous finish or a striking shoe can carry the entire look. Everything else can remain beautifully quiet."], ["Dress for the memory", "The pieces worth keeping are the ones that become part of the story. Choose something that feels like you, only more fully expressed."]] },
  "modern-femininity": { tag: "Fashion", title: "Modern Femininity, Reframed", dek: "A new perspective on confidence, movement and personal style.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F6c87aec0389744e9917cadd6e0d6236d?format=webp&width=1400&quality=95", intro: "Modern femininity is not one silhouette or a single way of being seen. It is the freedom to move between softness and strength on your own terms.", sections: [["Confidence has a quiet side", "A considered look does not need to announce itself. The right line, fit and texture can make confidence feel instinctive."], ["Movement is part of the design", "Clothes become personal when they move with the life inside them. Ease and structure can exist in the same piece."], ["Style is a conversation", "The most lasting style is responsive. It changes with experience while keeping hold of the details that feel unmistakably yours."]] }
} as const;

type Article = (typeof articles)[keyof typeof articles];

const JournalArticle = () => {
  const { slug } = useParams();
  const fallbackArticle = articles[slug as keyof typeof articles] as Article | undefined;
  const [cmsArticle, setCmsArticle] = useState<BuilderEditorialData | null>(null);

  useEffect(() => {
    setCmsArticle(null);
    if (!slug) return;
    void fetchBuilderEditorial(slug).then((data) => {
      if (data) setCmsArticle(data);
    });
  }, [slug]);

  const article = cmsArticle
    ? { tag: cmsArticle.category || cmsArticle.type || "Journal", title: cmsArticle.title, dek: cmsArticle.excerpt || fallbackArticle?.dek || "Stories and considered inspiration from Amelie Milano.", image: cmsArticle.heroImage || fallbackArticle?.image || "/placeholder.svg", intro: cmsArticle.excerpt || fallbackArticle?.intro || "Stories and considered inspiration from Amelie Milano.", sections: fallbackArticle?.sections || [] }
    : fallbackArticle;
  useEffect(() => {
    if (!article || !slug) return;
    const description = article.dek;
    const canonicalUrl = `${window.location.origin}/journal/${slug}`;
    document.title = `${article.title} | Amelie Milano Journal`;
    const setMeta = (selector: string, attributes: Record<string, string>) => { let element = document.head.querySelector<HTMLMetaElement>(selector); if (!element) { element = document.createElement("meta"); document.head.appendChild(element); } Object.entries(attributes).forEach(([key, value]) => element!.setAttribute(key, value)); };
    setMeta('meta[name="description"]', { name: "description", content: description });
    setMeta('meta[property="og:title"]', { property: "og:title", content: `${article.title} | Amelie Milano Journal` });
    setMeta('meta[property="og:description"]', { property: "og:description", content: description });
    setMeta('meta[property="og:image"]', { property: "og:image", content: article.image });
    setMeta('meta[property="og:type"]', { property: "og:type", content: "article" });
    let canonical = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if (!canonical) { canonical = document.createElement("link"); canonical.rel = "canonical"; document.head.appendChild(canonical); } canonical.href = canonicalUrl;
    let script = document.head.querySelector<HTMLScriptElement>('script[data-amelie-article-schema="true"]'); if (!script) { script = document.createElement("script"); script.type = "application/ld+json"; script.dataset.amelieArticleSchema = "true"; document.head.appendChild(script); }
    script.textContent = JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: article.title, description, image: [article.image], author: { "@type": "Person", name: "Amelie Milano" }, publisher: { "@type": "Organization", name: "Amelie Milano", url: window.location.origin }, mainEntityOfPage: canonicalUrl });
  }, [article, slug]);
  if (!article) return <div className="min-h-screen bg-[#F0E9E2] text-stone-900"><Header /><main className="container mx-auto px-4 py-24 text-center"><h1 className="font-serif text-5xl mb-5">Story not found</h1><Link to="/journal" className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-teal"><ArrowLeft size={15} /> Back to the Journal</Link></main><Footer /></div>;
  return <div className="min-h-screen bg-[#F0E9E2] text-stone-900"><Header /><main><div className="container mx-auto px-4 pt-8"><Breadcrumbs items={[{ label: "Journal", href: "/journal" }, { label: article.title }]} /></div><section className="relative min-h-[520px] md:h-[620px] overflow-hidden flex items-end bg-stone-900"><img src={article.image} alt={article.title} className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-stone-950/80 via-stone-950/25 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-14 md:pb-20 text-white"><Link to="/journal" className="mb-8 inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-white/80 hover:text-white"><ArrowLeft size={15} /> The Journal</Link><p className="text-[10px] uppercase tracking-[0.28em] text-white/80 mb-4">{article.tag}</p><h1 className="font-serif text-5xl md:text-8xl leading-[0.88] max-w-4xl mb-5">{article.title}</h1><p className="max-w-xl text-sm md:text-base text-white/85 leading-relaxed">{article.dek}</p></div></section><article className="bg-white py-16 md:py-24"><div className="container mx-auto max-w-3xl px-4"><div className="mb-12 flex items-center justify-between border-b border-stone-200 pb-5 text-[10px] uppercase tracking-[0.18em] text-stone-500"><span>Amelie Milano Journal</span><span>Editorial story</span></div><p className="font-serif text-3xl md:text-5xl leading-tight text-teal mb-14">{article.intro}</p><div className="space-y-12">{article.sections.map(([heading, copy], index) => <section key={heading}><p className="mb-3 text-[10px] uppercase tracking-[0.22em] text-teal">{String(index + 1).padStart(2, "0")}</p><h2 className="font-serif text-3xl md:text-4xl mb-4">{heading}</h2><p className="text-stone-600 leading-8">{copy}</p></section>)}</div><div className="mt-16 border-t border-stone-200 pt-8"><Link to="/shop" className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-teal hover:text-teal-dark">Explore the wardrobe <ChevronRight size={15} /></Link></div></div></article><section className="bg-[#E8D7C5] py-16 text-center"><div className="container mx-auto px-4"><p className="text-teal text-[10px] uppercase tracking-[0.24em] mb-3">More from Amelie</p><h2 className="font-serif text-4xl mb-5">Continue reading</h2><Link to="/journal" className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-teal">View all stories <ArrowRight size={15} /></Link></div></section></main><Footer /></div>;
};

export default JournalArticle;
