import { Link } from "react-router-dom";
import { ArrowRight, ChevronRight } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Breadcrumbs from "@/components/Breadcrumbs";

const articles = [
  { tag: "Fashion", title: "The Art of Italian Tailoring", copy: "Explore the quiet craft behind a considered silhouette.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F92b67c169b484849bc0557782bc3580b?format=webp&width=1000&quality=95", href: "/journal/italian-tailoring" },
  { tag: "Style Tips", title: "Building a Wardrobe With Ease", copy: "The pieces, proportions and textures that make dressing feel effortless.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F25041026487d4444b5d4fdcd8344b030?format=webp&width=1200&height=1800&quality=95", href: "/journal/wardrobe-essentials" },
  { tag: "Lifestyle", title: "A Softer Pace of Living", copy: "Finding beauty in the rituals that shape an ordinary day.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F8643453bf7a947959862f314163ce4f6?format=webp&width=1200&height=1800&quality=95", href: "/journal/softer-pace" },
  { tag: "Editorial", title: "The Occasion Edit", copy: "Dressing for evenings that deserve to be remembered.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Feddf3358484d4793b2020549afc8bf06?format=webp&width=1200&height=1800&quality=95", href: "/journal/occasion-edit" },
  { tag: "Fashion", title: "Modern Femininity, Reframed", copy: "A new perspective on confidence, movement and personal style.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F6c87aec0389744e9917cadd6e0d6236d?format=webp&width=1200&height=1800&quality=95", href: "/journal/modern-femininity" },
  { tag: "Lifestyle", title: "Inspiration in the Details", copy: "How the smallest choices can become the most distinctive ones.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F1b6c5c5bfe8a405f929f02fb57a189bb?format=webp&width=1200&height=1800&quality=95", href: "/journal/details" },
];

const Journal = () => (
  <div className="min-h-screen bg-[#F0E9E2] text-[#0F0F0F]"><Header /><main><div className="container mx-auto px-4 pt-8"><Breadcrumbs items={[{ label: "Journal" }]} /></div>
    <section className="relative min-h-[580px] md:h-[660px] overflow-hidden flex items-end bg-stone-900"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Fbbfd759960964ecdb9963d81ba7b70a6?format=webp&width=800&height=1200" alt="Amelie Milano Journal" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-stone-950/70 via-stone-950/15 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-16 md:pb-20 text-white"><p className="text-[10px] uppercase tracking-[0.28em] text-white/80 mb-5">The Journal</p><h1 className="font-serif text-6xl md:text-8xl leading-[0.86] max-w-3xl mb-6">Amelie Milano Journal</h1><p className="text-sm md:text-base text-white/85 max-w-md leading-relaxed mb-8">Stories, inspirations and lifestyle insights from the world of Amelie Milano.</p><Link to="#articles" className="inline-flex items-center gap-3 bg-[#C69B6D] px-6 py-3 text-xs uppercase tracking-[0.16em] text-stone-900 hover:bg-white transition-colors">Explore Articles <ArrowRight size={15} /></Link></div></section>
    <section id="articles" className="bg-[#F0E9E2] py-20 md:py-32"><div className="container mx-auto px-4 max-w-6xl"><div className="grid md:grid-cols-[1.2fr_0.8fr] gap-8 md:gap-16 items-center mb-20"><Link to={articles[0].href} className="group overflow-hidden"><img src={articles[0].image} alt={articles[0].title} className="w-full aspect-[16/10] object-cover group-hover:scale-[1.02] transition-transform duration-500" /></Link><div><p className="text-teal text-[10px] uppercase tracking-[0.24em] mb-4">Spotlight · {articles[0].tag}</p><h2 className="font-serif text-4xl md:text-5xl mb-5">{articles[0].title}</h2><p className="text-stone-600 leading-relaxed mb-7">{articles[0].copy} Discover the heritage and intention behind the pieces that define the Amelie wardrobe.</p><Link to={articles[0].href} className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-teal">Read More <ChevronRight size={15} /></Link></div></div><div className="flex flex-wrap justify-center gap-4 border-y border-stone-300 py-5 mb-12"><span className="text-xs uppercase tracking-[0.16em] text-teal">All Stories</span><span className="text-xs uppercase tracking-[0.16em] text-stone-500">Fashion</span><span className="text-xs uppercase tracking-[0.16em] text-stone-500">Lifestyle</span><span className="text-xs uppercase tracking-[0.16em] text-stone-500">Style Tips</span><span className="text-xs uppercase tracking-[0.16em] text-stone-500">Editorial</span></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-14">{articles.slice(1).map((article) => <article key={article.title} className="group"><Link to={article.href}><div className="overflow-hidden mb-5"><img src={article.image} alt={article.title} className="w-full aspect-[4/3] object-cover group-hover:scale-[1.03] transition-transform duration-500" /></div><p className="text-teal text-[10px] uppercase tracking-[0.2em] mb-3">{article.tag}</p><h3 className="font-serif text-2xl group-hover:text-teal transition-colors">{article.title}</h3><p className="text-sm text-stone-600 leading-relaxed mt-3">{article.copy}</p><span className="mt-4 inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-teal">Read More <ChevronRight size={14} /></span></Link></article>)}</div></div></section>
    <section className="bg-white py-16 md:py-24"><div className="container mx-auto px-4 max-w-4xl"><div className="grid md:grid-cols-2 gap-10 md:gap-20 items-center"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F55baf11751a34a54b0e32d4dfe3b2e9f?format=webp&width=1600&height=2400&quality=95" alt="Journal style details" className="w-full aspect-[4/5] object-cover" /><div><p className="text-teal text-[10px] uppercase tracking-[0.24em] mb-4">From the editor</p><blockquote className="font-serif italic text-3xl md:text-4xl leading-tight mb-6">“Style begins where intention meets instinct.”</blockquote><p className="text-stone-600 leading-relaxed">The Journal is our space for thoughtful ideas, styling notes and the references behind each collection.</p></div></div></div></section>
    <section className="bg-[#E8D7C5] py-16 md:py-24 text-center"><div className="container mx-auto px-4 max-w-2xl"><h2 className="font-serif text-4xl md:text-6xl mb-5">Stay Inspired</h2><p className="text-stone-600 mb-8">Join the Journal for new stories, style notes and seasonal inspiration.</p><form onSubmit={(event) => event.preventDefault()} className="mx-auto flex max-w-md border-b border-stone-700"><input type="email" placeholder="Your email address" className="min-w-0 flex-1 bg-transparent px-0 py-3 text-sm focus:outline-none" /><button type="submit" className="bg-[#C69B6D] px-5 py-2 text-xs uppercase tracking-[0.16em] text-stone-900 hover:bg-white transition-colors">Join the Journal</button></form></div></section>
  </main><Footer /></div>
);
export default Journal;
