import { Link } from "react-router-dom";
import { ArrowRight, ChevronRight } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const stories = [
  { eyebrow: "Craftsmanship", title: "The Art of Italian Tailoring", copy: "Explore how centuries of fashion heritage inspire every considered stitch in the Amelie collection.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F92b67c169b484849bc0557782bc3580b?format=webp&width=1200&quality=95", href: "/journal/italian-tailoring" },
  { eyebrow: "The Journey", title: "A Wardrobe With A Point Of View", copy: "Meet the textures, silhouettes and places that shape the Amelie Milano woman.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Fc09eb3a2d9da4b20b5d3d99979a90b4f?format=webp&width=1200&quality=95", href: "/brand-story" },
  { eyebrow: "Style Guide", title: "The Modern Occasion Edit", copy: "A study in ease, elegance and the art of dressing for your most memorable moments.", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F3abee068625f43fbb7ab80d054951ad7?format=webp&width=1200&quality=95", href: "/journal/occasion-edit" },
];

const collections = [
  { label: "Dresses", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Fd82ccb0930fd4d0e8a2edb49f49368e1?format=webp&width=900&height=1200", href: "/shop/dresses" },
  { label: "Occasionwear", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2Ff2edad5f9989469e9179290f0356a25b?format=webp&width=900&height=1200", href: "/shop/occasionwear" },
  { label: "Bags", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900&h=1200&fit=crop", href: "/shop/bags" },
  { label: "Shoes", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F63618dadc38341448c40401de698c1a3?format=webp&width=900&height=1200", href: "/shop/shoes" },
  { label: "Gym Wear", image: "https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F56076a5843aa49afaee6765ec232fb48?format=webp&width=900&height=1200", href: "/shop/gym-wear" },
];

const TheAmelieEdit = () => (
  <div className="min-h-screen bg-[#F8F4EE] text-[#333333]">
    <Header />
    <main>
      <section className="relative min-h-[620px] md:h-[700px] overflow-hidden bg-[#F8F4EE] flex items-end"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F374cefe0384f47368b124dd5de150597?format=webp&width=1800&quality=95" alt="The Amelie Edit campaign" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-stone-950/65 via-stone-950/15 to-transparent" /><div className="relative z-10 container mx-auto px-4 pb-16 md:pb-20 text-white"><p className="text-[10px] uppercase tracking-[0.28em] text-white/80 mb-5">The Amelie Edit</p><h1 className="font-serif text-6xl md:text-8xl leading-[0.86] max-w-2xl mb-6">The Amelie Edit</h1><p className="text-sm md:text-base text-white/85 max-w-md leading-relaxed mb-8">Curated selection of European-inspired pieces that define contemporary femininity.</p><Link to="#stories" className="inline-flex items-center gap-3 bg-[#F9B233] px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-stone-900 hover:bg-white transition-colors">Explore The Edit <ArrowRight size={15} /></Link></div></section>

      <section id="stories" className="bg-[#F8F4EE] py-20 md:py-32"><div className="container mx-auto px-4 max-w-6xl"><div className="text-center max-w-2xl mx-auto mb-14 md:mb-20"><p className="text-[#005F91] text-[10px] uppercase tracking-[0.28em] mb-5">The Journal</p><h2 className="font-serif text-4xl md:text-6xl mb-5">Stories with a point of view.</h2><p className="text-stone-600 leading-relaxed">Discover the people, places and ideas behind Amelie Milano — a visual journal of modern femininity.</p></div><div className="grid md:grid-cols-3 gap-6 md:gap-8">{stories.map((story) => <article key={story.title} className="group"><Link to={story.href}><div className="relative overflow-hidden mb-5"><img src={story.image} alt={story.title} className="w-full aspect-[3/4] object-cover group-hover:scale-[1.03] transition-transform duration-500" /><div className="absolute inset-0 bg-stone-950/0 group-hover:bg-stone-950/30 transition-colors flex items-end p-5"><span className="text-white text-xs uppercase tracking-[0.16em] opacity-0 group-hover:opacity-100 transition-opacity">Read More <ChevronRight className="inline" size={14} /></span></div></div><p className="text-[#005F91] text-[10px] uppercase tracking-[0.2em] mb-3">{story.eyebrow}</p><h3 className="font-serif text-2xl group-hover:text-[#005F91] transition-colors">{story.title}</h3><p className="text-sm text-stone-600 mt-3 leading-relaxed">{story.copy}</p></Link></article>)}</div></div></section>

      <section className="bg-white py-16 md:py-24"><div className="container mx-auto px-4"><div className="text-center mb-10"><p className="text-[#005F91] text-[10px] uppercase tracking-[0.28em] mb-3">Curated Collections</p><h2 className="font-serif text-4xl md:text-5xl">Explore the wardrobe</h2></div><div className="grid grid-cols-2 md:grid-cols-5 gap-4 md:gap-6">{collections.map((collection) => <Link to={collection.href} key={collection.label} className="group"><div className="overflow-hidden mb-4"><img src={collection.image} alt={collection.label} className="w-full aspect-[3/4] object-cover group-hover:scale-[1.03] transition-transform duration-500" /></div><h3 className="font-serif text-xl group-hover:text-[#005F91] transition-colors">{collection.label}</h3><span className="mt-2 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.16em] text-[#005F91]">Shop Collection <ChevronRight size={13} /></span></Link>)}</div></div></section>

      <section className="bg-[#F8F4EE] py-16 md:py-24"><div className="container mx-auto px-4 max-w-6xl"><div className="grid md:grid-cols-2 gap-10 md:gap-20 items-center"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F92b67c169b484849bc0557782bc3580b?format=webp&width=1400&quality=95" alt="Fashion details and style inspiration" className="w-full aspect-[4/5] object-cover" /><div className="max-w-md"><p className="text-[#005F91] text-[10px] uppercase tracking-[0.24em] mb-4">Style Guides</p><h2 className="font-serif text-4xl md:text-5xl mb-5">The art of the considered wardrobe.</h2><p className="text-stone-600 leading-relaxed mb-7">Mix refined staples with statement silhouettes, play with proportion and let one beautiful detail lead the way.</p><Link to="/journal" className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-[#005F91]">Discover Style Tips <ArrowRight size={15} /></Link></div></div></div></section>

      <section className="bg-white py-16 md:py-24"><div className="container mx-auto px-4"><div className="relative overflow-hidden min-h-[420px] flex items-end"><img src="https://cdn.builder.io/api/v1/image/assets%2F661d1ac868bc41caba3d7f46cd61e3ce%2F3abee068625f43fbb7ab80d054951ad7?format=webp&width=1800&quality=95" alt="Amelie Milano lifestyle" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-stone-950/65 to-transparent" /><div className="relative z-10 p-8 md:p-16 text-white max-w-xl"><p className="text-[10px] uppercase tracking-[0.28em] text-white/80 mb-4">A Season in Focus</p><h2 className="font-serif text-4xl md:text-6xl mb-5">Modern femininity, beautifully lived.</h2><p className="text-sm text-white/80 leading-relaxed">A closer look at the textures, places and silhouettes defining the season.</p></div></div></div></section>

      <section className="bg-[#E8D7C5] py-16 md:py-24"><div className="container mx-auto px-4 text-center max-w-2xl"><p className="text-[#005F91] text-[10px] uppercase tracking-[0.26em] mb-5">The Amelie Edit</p><h2 className="font-serif text-4xl md:text-6xl mb-6">Stay Updated with The Amelie Edit</h2><p className="text-stone-600 mb-8">Receive new stories, seasonal inspiration and considered styling notes from Amelie Milano.</p><form onSubmit={(event) => event.preventDefault()} className="mx-auto flex max-w-md border-b border-stone-700"><input type="email" placeholder="Your email address" className="min-w-0 flex-1 bg-transparent px-0 py-3 text-sm focus:outline-none" /><button type="submit" className="bg-[#F9B233] px-5 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-stone-900 hover:bg-white transition-colors">Subscribe Now</button></form></div></section>
    </main>
    <Footer />
  </div>
);

export default TheAmelieEdit;
